import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../auth/presentation/providers/user_profile_provider.dart';
import '../../../subscription/presentation/providers/subscription_provider.dart';
import '../../domain/models/lesson.dart';

// 레슨 목데이터
final _allLessons = <Lesson>[
  // ─── 피아노 입문 ───
  Lesson(
    id: 'piano_001',
    title: '도레미파솔라시도',
    description: '피아노의 기초! C장조 음계를 연습해 봅시다. 각 건반의 위치를 익히고 부드럽게 연주해 보세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 5,
    imageEmoji: '🎹',
    bpm: 60,
    xpReward: 100,
    orderIndex: 1,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 1.0, order: 0),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 1.0, duration: 1.0, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.0, duration: 1.0, order: 2),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 3.0, duration: 1.0, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.0, duration: 1.0, order: 4),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 5.0, duration: 1.0, order: 5),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 6.0, duration: 1.0, order: 6),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 7.0, duration: 1.0, order: 7),
    ],
  ),
  Lesson(
    id: 'piano_002',
    title: '반짝반짝 작은별',
    description: '누구나 아는 동요! 멜로디를 따라 피아노로 연주해 보세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '⭐',
    bpm: 70,
    xpReward: 150,
    orderIndex: 2,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.8, order: 0),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.8, duration: 0.8, order: 1),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.6, duration: 0.8, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.4, duration: 0.8, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 3.2, duration: 0.8, order: 4),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.0, duration: 0.8, order: 5),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.8, duration: 1.6, order: 6),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 6.4, duration: 0.8, order: 7),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 7.2, duration: 0.8, order: 8),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 8.0, duration: 0.8, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 8.8, duration: 0.8, order: 10),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 9.6, duration: 0.8, order: 11),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 10.4, duration: 0.8, order: 12),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 11.2, duration: 1.6, order: 13),
    ],
  ),
  Lesson(
    id: 'piano_003',
    title: '비행기',
    description: '경쾌한 동요 "비행기"를 피아노로 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '✈️',
    bpm: 80,
    xpReward: 150,
    orderIndex: 3,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.75, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.75, duration: 0.75, order: 1),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.5, duration: 1.5, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.0, duration: 0.75, order: 3),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.75, duration: 0.75, order: 4),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.5, duration: 1.5, order: 5),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.0, duration: 0.75, order: 6),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.75, duration: 0.75, order: 7),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 7.5, duration: 1.5, order: 8),
    ],
  ),
  Lesson(
    id: 'piano_s01',
    title: 'G장조 음계',
    description: 'G장조 스케일을 연습합니다. #파(F#)에 주의하세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 5,
    imageEmoji: '🎹',
    bpm: 60,
    xpReward: 100,
    orderIndex: 2,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.0, duration: 1.0, order: 0),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.0, duration: 1.0, order: 1),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 2.0, duration: 1.0, order: 2),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 3.0, duration: 1.0, order: 3),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.0, duration: 1.0, order: 4),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 5.0, duration: 1.0, order: 5),
      MusicNote(noteName: 'F#4', frequency: NoteFrequency.fSharp4, startTime: 6.0, duration: 1.0, order: 6),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 7.0, duration: 1.0, order: 7),
    ],
  ),
  Lesson(
    id: 'piano_n01',
    title: '나비야 나비야',
    description: '한국 대표 동요! 쉽고 즐거운 멜로디를 피아노로 연주해 보세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '🦋',
    bpm: 80,
    xpReward: 130,
    orderIndex: 3,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.0, duration: 0.75, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.75, duration: 0.75, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.5, duration: 1.5, order: 2),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 3.0, duration: 0.75, order: 3),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.75, duration: 0.75, order: 4),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 4.5, duration: 1.5, order: 5),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 6.0, duration: 0.75, order: 6),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 6.75, duration: 0.75, order: 7),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 7.5, duration: 0.75, order: 8),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 8.25, duration: 0.75, order: 9),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 9.0, duration: 0.75, order: 10),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 9.75, duration: 0.75, order: 11),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 10.5, duration: 1.5, order: 12),
    ],
  ),
  Lesson(
    id: 'piano_n02',
    title: '곰 세 마리',
    description: '엄마곰 아빠곰 애기곰! 아이들이 좋아하는 동요를 피아노로 연주해 보세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 7,
    imageEmoji: '🐻',
    bpm: 85,
    xpReward: 140,
    orderIndex: 4,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.4, duration: 0.7, order: 2),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 2.1, duration: 0.7, order: 3),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 2.8, duration: 0.7, order: 4),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.5, duration: 0.7, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 4.2, duration: 0.7, order: 6),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 4.9, duration: 0.7, order: 7),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 5.6, duration: 0.7, order: 8),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 6.3, duration: 0.7, order: 9),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 7.0, duration: 1.4, order: 10),
    ],
  ),
  Lesson(
    id: 'piano_n03',
    title: '산토끼',
    description: '산토끼 토끼야! 신나는 동요를 피아노로 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 7,
    imageEmoji: '🐰',
    bpm: 90,
    xpReward: 140,
    orderIndex: 5,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.66, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.66, duration: 0.66, order: 1),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 1.32, duration: 0.66, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.98, duration: 0.66, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.64, duration: 0.66, order: 4),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 3.3, duration: 0.66, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.96, duration: 0.66, order: 6),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 4.62, duration: 0.66, order: 7),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 5.28, duration: 0.66, order: 8),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 5.94, duration: 0.66, order: 9),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 6.6, duration: 0.66, order: 10),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 7.26, duration: 1.32, order: 11),
    ],
  ),
  Lesson(
    id: 'piano_c01',
    title: '환희의 송가 (베토벤)',
    description: '베토벤 교향곡 9번의 유명한 선율! 간단한 멜로디로 클래식에 입문해 보세요.',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 10,
    imageEmoji: '🎼',
    bpm: 80,
    xpReward: 250,
    orderIndex: 6,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.75, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.75, duration: 0.75, order: 1),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 1.5, duration: 0.75, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.25, duration: 0.75, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.0, duration: 0.75, order: 4),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 3.75, duration: 0.75, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 4.5, duration: 0.75, order: 6),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 5.25, duration: 0.75, order: 7),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 6.0, duration: 0.75, order: 8),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 6.75, duration: 0.75, order: 9),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.5, duration: 0.75, order: 10),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 8.25, duration: 0.75, order: 11),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 9.0, duration: 1.1, order: 12),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 10.1, duration: 0.4, order: 13),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 10.5, duration: 1.5, order: 14),
    ],
  ),
  Lesson(
    id: 'piano_004',
    title: '엘리제를 위하여 (인트로)',
    description: '베토벤의 명곡! 가장 유명한 클래식 피아노 곡의 도입부를 배워봅시다.',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 15,
    imageEmoji: '🎼',
    bpm: 90,
    xpReward: 300,
    orderIndex: 4,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.5, order: 0),
      MusicNote(noteName: 'D#4', frequency: NoteFrequency.dSharp4, startTime: 0.5, duration: 0.5, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.0, duration: 0.5, order: 2),
      MusicNote(noteName: 'D#4', frequency: NoteFrequency.dSharp4, startTime: 1.5, duration: 0.5, order: 3),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.0, duration: 0.5, order: 4),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 2.5, duration: 0.5, order: 5),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.0, duration: 0.5, order: 6),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 3.5, duration: 0.5, order: 7),
      MusicNote(noteName: 'A3', frequency: NoteFrequency.a3, startTime: 4.0, duration: 1.0, order: 8),
    ],
  ),

  // ─── 드럼 입문 ───
  Lesson(
    id: 'drums_001',
    title: '드럼 기초 - 4비트 패턴',
    description: '드럼의 기본! 킥(K)과 스네어(S)로 가장 기본적인 4비트 리듬을 익혀봅시다.',
    instrument: 'drums',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🥁',
    bpm: 70,
    xpReward: 120,
    orderIndex: 1,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.5, order: 0),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.0, duration: 0.5, order: 1),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 2.0, duration: 0.5, order: 2),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 3.0, duration: 0.5, order: 3),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 4.0, duration: 0.5, order: 4),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 5.0, duration: 0.5, order: 5),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 6.0, duration: 0.5, order: 6),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 7.0, duration: 0.5, order: 7),
    ],
  ),
  Lesson(
    id: 'drums_002',
    title: '드럼 기초 - 하이햇 추가',
    description: '킥·스네어에 하이햇(HH)을 더해 풍성한 8비트 리듬을 만들어 보세요.',
    instrument: 'drums',
    difficulty: 'beginner',
    durationMinutes: 10,
    imageEmoji: '🎶',
    bpm: 80,
    xpReward: 150,
    orderIndex: 2,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.0, duration: 0.4, order: 0),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.4, order: 1),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.5, duration: 0.4, order: 2),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.0, duration: 0.4, order: 3),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.5, duration: 0.4, order: 4),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 2.0, duration: 0.4, order: 5),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 2.5, duration: 0.4, order: 6),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 3.0, duration: 0.4, order: 7),
    ],
  ),
  Lesson(
    id: 'drums_003',
    title: '드럼 - 록 비트',
    description: '록 음악의 기본 드럼 패턴을 배워봅시다. 에너지 넘치는 리듬!',
    instrument: 'drums',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🤘',
    bpm: 100,
    xpReward: 250,
    orderIndex: 3,
    category: 'scale',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.3, order: 0),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.3, duration: 0.3, order: 1),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.6, duration: 0.3, order: 2),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.9, duration: 0.3, order: 3),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 1.2, duration: 0.3, order: 4),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.5, duration: 0.3, order: 5),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 1.8, duration: 0.3, order: 6),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 2.1, duration: 0.3, order: 7),
    ],
  ),

  // ─── 바이올린 입문 ───
  Lesson(
    id: 'violin_001',
    title: '바이올린 개방현 4개',
    description: '바이올린의 4개 개방현(G·D·A·E)을 활로 올바르게 긋는 연습을 시작해 봅시다.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🎻',
    bpm: 50,
    xpReward: 120,
    orderIndex: 1,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'G3', frequency: NoteFrequency.g3, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),
  Lesson(
    id: 'violin_002',
    title: '반짝반짝 작은별 (바이올린)',
    description: '바이올린으로 반짝반짝 작은별을 연주해 봅시다. A현을 주로 사용합니다.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 10,
    imageEmoji: '⭐',
    bpm: 65,
    xpReward: 160,
    orderIndex: 2,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.0, duration: 0.8, order: 0),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.8, duration: 0.8, order: 1),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 1.6, duration: 0.8, order: 2),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 2.4, duration: 0.8, order: 3),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 3.2, duration: 0.8, order: 4),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 4.0, duration: 0.8, order: 5),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 4.8, duration: 1.6, order: 6),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 6.4, duration: 0.8, order: 7),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 7.2, duration: 0.8, order: 8),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 8.0, duration: 0.8, order: 9),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 8.8, duration: 0.8, order: 10),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 9.6, duration: 0.8, order: 11),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 10.4, duration: 1.6, order: 12),
    ],
  ),
  Lesson(
    id: 'violin_003',
    title: '아리랑 (바이올린)',
    description: '바이올린으로 연주하는 아리랑. D현과 A현을 번갈아 사용합니다.',
    instrument: 'violin',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🇰🇷',
    bpm: 70,
    xpReward: 260,
    orderIndex: 3,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.0, duration: 0.8, order: 0),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 0.8, duration: 0.8, order: 1),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 1.6, duration: 1.6, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 3.2, duration: 0.8, order: 3),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 4.0, duration: 1.6, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 5.6, duration: 0.8, order: 5),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.4, duration: 1.6, order: 6),
    ],
  ),

  Lesson(
    id: 'violin_n01',
    title: '나비야 나비야 (바이올린)',
    description: '동요 나비야를 바이올린으로 연주해 봅시다. A현과 E현을 사용합니다.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🦋',
    bpm: 75,
    xpReward: 150,
    orderIndex: 3,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.0, duration: 0.8, order: 0),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 0.8, duration: 0.8, order: 1),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.6, duration: 1.6, order: 2),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 3.2, duration: 0.8, order: 3),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 4.0, duration: 0.8, order: 4),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 4.8, duration: 1.6, order: 5),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.4, duration: 0.8, order: 6),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 7.2, duration: 0.8, order: 7),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 8.0, duration: 0.8, order: 8),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 8.8, duration: 0.8, order: 9),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 9.6, duration: 0.8, order: 10),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 10.4, duration: 1.6, order: 11),
    ],
  ),

  // ─── 기타 입문 ───
  Lesson(
    id: 'guitar_001',
    title: '기타 기초 - Am 코드',
    description: 'Am 코드는 기타의 시작! 올바른 운지법으로 맑은 소리를 내는 방법을 배워봅시다.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 10,
    imageEmoji: '🎸',
    bpm: 60,
    xpReward: 120,
    orderIndex: 1,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'A2', frequency: 110.00, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'A2', frequency: 110.00, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'A2', frequency: 110.00, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'A2', frequency: 110.00, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),
  Lesson(
    id: 'guitar_002',
    title: '기타 기초 - G 코드',
    description: 'G 코드를 마스터하면 수많은 노래를 연주할 수 있어요. Am과 함께 연습해 봅시다.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 10,
    imageEmoji: '🎵',
    bpm: 60,
    xpReward: 120,
    orderIndex: 2,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'G2', frequency: 98.00, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'G2', frequency: 98.00, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'G2', frequency: 98.00, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'G2', frequency: 98.00, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),
  Lesson(
    id: 'guitar_003',
    title: '아리랑',
    description: '우리나라 대표 민요 아리랑을 기타로 연주해 봅시다.',
    instrument: 'guitar',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🇰🇷',
    bpm: 75,
    xpReward: 250,
    orderIndex: 3,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.8, order: 0),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 0.8, duration: 0.8, order: 1),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 1.6, duration: 1.6, order: 2),
      MusicNote(noteName: 'A3', frequency: NoteFrequency.a3, startTime: 3.2, duration: 0.8, order: 3),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 4.0, duration: 1.6, order: 4),
    ],
  ),

  // ═══════════════════════════════════════════════════════
  // ─── 추가 음계 레슨 (Scale) ───
  // ═══════════════════════════════════════════════════════

  // Scale 1: Piano - D장조 음계
  Lesson(
    id: 'piano_s02',
    title: 'D장조 음계',
    description: 'D장조 스케일을 연습합니다. C#과 F#에 주의하세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 5,
    imageEmoji: '🎹',
    bpm: 60,
    xpReward: 100,
    orderIndex: 20,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 0.0, duration: 1.0, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.0, duration: 1.0, order: 1),
      MusicNote(noteName: 'F#4', frequency: NoteFrequency.fSharp4, startTime: 2.0, duration: 1.0, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.0, duration: 1.0, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.0, duration: 1.0, order: 4),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 5.0, duration: 1.0, order: 5),
      MusicNote(noteName: 'C#5', frequency: 554.37, startTime: 6.0, duration: 1.0, order: 6),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 7.0, duration: 1.0, order: 7),
    ],
  ),

  // Scale 2: Piano - F장조 음계
  Lesson(
    id: 'piano_s03',
    title: 'F장조 음계',
    description: 'F장조 스케일을 연습합니다. Bb(시플랫)에 주의하세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 5,
    imageEmoji: '🎹',
    bpm: 60,
    xpReward: 100,
    orderIndex: 21,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 0.0, duration: 1.0, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.0, duration: 1.0, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 2.0, duration: 1.0, order: 2),
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 3.0, duration: 1.0, order: 3),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 4.0, duration: 1.0, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 5.0, duration: 1.0, order: 5),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.0, duration: 1.0, order: 6),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 7.0, duration: 1.0, order: 7),
    ],
  ),

  // Scale 3: Guitar - E 코드
  Lesson(
    id: 'guitar_s01',
    title: 'E 코드',
    description: '기타 E 메이저 코드를 연습합니다. 풍성한 울림을 느껴보세요.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🎸',
    bpm: 60,
    xpReward: 110,
    orderIndex: 22,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'E2', frequency: 82.41, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'E2', frequency: 82.41, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'E2', frequency: 82.41, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'E2', frequency: 82.41, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),

  // Scale 4: Guitar - C 코드
  Lesson(
    id: 'guitar_s02',
    title: 'C 코드',
    description: '기타 C 메이저 코드를 연습합니다. 가장 많이 쓰이는 코드 중 하나입니다.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🎸',
    bpm: 60,
    xpReward: 110,
    orderIndex: 23,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'C3', frequency: 130.81, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'C3', frequency: 130.81, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'C3', frequency: 130.81, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'C3', frequency: 130.81, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),

  // Scale 5: Guitar - D 코드
  Lesson(
    id: 'guitar_s03',
    title: 'D 코드',
    description: '기타 D 메이저 코드를 연습합니다. G, C 코드와 함께 자주 쓰입니다.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🎸',
    bpm: 60,
    xpReward: 110,
    orderIndex: 24,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'D3', frequency: NoteFrequency.d3, startTime: 0.0, duration: 2.0, order: 0),
      MusicNote(noteName: 'D3', frequency: NoteFrequency.d3, startTime: 2.0, duration: 2.0, order: 1),
      MusicNote(noteName: 'D3', frequency: NoteFrequency.d3, startTime: 4.0, duration: 2.0, order: 2),
      MusicNote(noteName: 'D3', frequency: NoteFrequency.d3, startTime: 6.0, duration: 2.0, order: 3),
    ],
  ),

  // Scale 6: Violin - D장조 음계
  Lesson(
    id: 'violin_s01',
    title: 'D장조 음계 (바이올린)',
    description: '바이올린으로 D장조 스케일을 연습합니다. D현과 A현을 사용합니다.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '🎻',
    bpm: 55,
    xpReward: 110,
    orderIndex: 25,
    category: 'scale',
    targetNotes: [
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 0.0, duration: 1.5, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.5, duration: 1.5, order: 1),
      MusicNote(noteName: 'F#4', frequency: NoteFrequency.fSharp4, startTime: 3.0, duration: 1.5, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.5, duration: 1.5, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.0, duration: 1.5, order: 4),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 7.5, duration: 1.5, order: 5),
      MusicNote(noteName: 'C#5', frequency: 554.37, startTime: 9.0, duration: 1.5, order: 6),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 10.5, duration: 1.5, order: 7),
    ],
  ),

  // Scale 7: Violin - A장조 음계
  Lesson(
    id: 'violin_s02',
    title: 'A장조 음계 (바이올린)',
    description: '바이올린으로 A장조 스케일을 연습합니다. A현에서 시작합니다.',
    instrument: 'violin',
    difficulty: 'intermediate',
    durationMinutes: 7,
    imageEmoji: '🎻',
    bpm: 55,
    xpReward: 150,
    orderIndex: 26,
    category: 'scale',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.0, duration: 1.5, order: 0),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 1.5, duration: 1.5, order: 1),
      MusicNote(noteName: 'C#5', frequency: 554.37, startTime: 3.0, duration: 1.5, order: 2),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.5, duration: 1.5, order: 3),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.0, duration: 1.5, order: 4),
      MusicNote(noteName: 'F#5', frequency: 739.99, startTime: 7.5, duration: 1.5, order: 5),
      MusicNote(noteName: 'G#5', frequency: 830.61, startTime: 9.0, duration: 1.5, order: 6),
      MusicNote(noteName: 'A5', frequency: NoteFrequency.a5, startTime: 10.5, duration: 1.5, order: 7),
    ],
  ),

  // Scale 8: Drums - 셔플 비트
  Lesson(
    id: 'drums_s01',
    title: '셔플 비트',
    description: '스윙감 있는 셔플 리듬을 연습합니다. 블루스와 재즈의 기본!',
    instrument: 'drums',
    difficulty: 'intermediate',
    durationMinutes: 10,
    imageEmoji: '🥁',
    bpm: 85,
    xpReward: 200,
    orderIndex: 27,
    category: 'scale',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.4, order: 0),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.0, duration: 0.3, order: 1),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.47, duration: 0.3, order: 2),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.7, duration: 0.4, order: 3),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.17, duration: 0.3, order: 4),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 1.4, duration: 0.4, order: 5),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.87, duration: 0.3, order: 6),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 2.1, duration: 0.4, order: 7),
    ],
  ),

  // Scale 9: Drums - 16비트 패턴
  Lesson(
    id: 'drums_s02',
    title: '16비트 패턴',
    description: '16비트 하이햇 패턴을 연습합니다. 펑크와 R&B의 기본 리듬!',
    instrument: 'drums',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🥁',
    bpm: 90,
    xpReward: 220,
    orderIndex: 28,
    category: 'scale',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.3, order: 0),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.0, duration: 0.15, order: 1),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.166, duration: 0.15, order: 2),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.333, duration: 0.15, order: 3),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.5, duration: 0.15, order: 4),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.666, duration: 0.3, order: 5),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.666, duration: 0.15, order: 6),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.833, duration: 0.15, order: 7),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.0, duration: 0.15, order: 8),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 1.0, duration: 0.3, order: 9),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.166, duration: 0.15, order: 10),
    ],
  ),

  // Scale 10: Piano - Am 펜타토닉 스케일
  Lesson(
    id: 'piano_s04',
    title: 'Am 펜타토닉 스케일',
    description: '즉흥 연주의 기초! Am 펜타토닉 스케일을 익혀봅시다.',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 7,
    imageEmoji: '🎹',
    bpm: 65,
    xpReward: 160,
    orderIndex: 29,
    category: 'scale',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.0, duration: 1.0, order: 0),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.0, duration: 1.0, order: 1),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 2.0, duration: 1.0, order: 2),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 3.0, duration: 1.0, order: 3),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 4.0, duration: 1.0, order: 4),
      MusicNote(noteName: 'A5', frequency: NoteFrequency.a5, startTime: 5.0, duration: 1.0, order: 5),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 6.0, duration: 1.0, order: 6),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 7.0, duration: 1.0, order: 7),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 8.0, duration: 1.0, order: 8),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 9.0, duration: 1.0, order: 9),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 10.0, duration: 1.0, order: 10),
    ],
  ),

  // ═══════════════════════════════════════════════════════
  // ─── 추가 동요 레슨 (Nursery) ───
  // ═══════════════════════════════════════════════════════

  // Nursery 1: Piano - 그대로 멈춰라
  Lesson(
    id: 'piano_n04',
    title: '그대로 멈춰라',
    description: '신나는 율동 동요! 피아노로 경쾌한 멜로디를 연주해 보세요.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '🛑',
    bpm: 100,
    xpReward: 130,
    orderIndex: 30,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.0, duration: 0.6, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.6, duration: 0.6, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.2, duration: 0.6, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.8, duration: 0.6, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.4, duration: 0.6, order: 4),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.0, duration: 0.6, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.6, duration: 1.2, order: 6),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.8, duration: 0.6, order: 7),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 5.4, duration: 0.6, order: 8),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 6.0, duration: 0.6, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 6.6, duration: 0.6, order: 10),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.2, duration: 1.2, order: 11),
    ],
  ),

  // Nursery 2: Piano - 작은별 변주곡
  Lesson(
    id: 'piano_n05',
    title: '작은별 변주곡',
    description: '모차르트의 작은별 변주곡 테마를 연주해 봅시다. 원곡보다 조금 빠르게!',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 8,
    imageEmoji: '⭐',
    bpm: 90,
    xpReward: 180,
    orderIndex: 31,
    category: 'nursery',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.66, order: 0),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.66, duration: 0.66, order: 1),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.32, duration: 0.66, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.98, duration: 0.66, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 2.64, duration: 0.66, order: 4),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 3.3, duration: 0.66, order: 5),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.96, duration: 1.32, order: 6),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 5.28, duration: 0.66, order: 7),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 5.94, duration: 0.66, order: 8),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 6.6, duration: 0.66, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 7.26, duration: 0.66, order: 10),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.92, duration: 0.66, order: 11),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 8.58, duration: 0.66, order: 12),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 9.24, duration: 1.32, order: 13),
    ],
  ),

  // Nursery 3: Piano - 학교종
  Lesson(
    id: 'piano_n06',
    title: '학교종',
    description: '학교종이 땡땡땡! 피아노로 밝고 경쾌하게 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '🔔',
    bpm: 90,
    xpReward: 130,
    orderIndex: 32,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.0, duration: 0.66, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.66, duration: 0.66, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.32, duration: 0.66, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.98, duration: 0.66, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.64, duration: 0.66, order: 4),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.3, duration: 0.66, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.96, duration: 1.32, order: 6),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 5.28, duration: 0.66, order: 7),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 5.94, duration: 0.66, order: 8),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 6.6, duration: 0.66, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 7.26, duration: 0.66, order: 10),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.92, duration: 1.32, order: 11),
    ],
  ),

  // Nursery 4: Guitar - 올챙이와 개구리
  Lesson(
    id: 'guitar_n01',
    title: '올챙이와 개구리',
    description: '기타로 연주하는 올챙이와 개구리! 단순한 멜로디로 기타에 익숙해져 보세요.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 7,
    imageEmoji: '🐸',
    bpm: 85,
    xpReward: 140,
    orderIndex: 33,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.4, duration: 0.7, order: 2),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 2.1, duration: 0.7, order: 3),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.8, duration: 0.7, order: 4),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.5, duration: 0.7, order: 5),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 4.2, duration: 1.4, order: 6),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 5.6, duration: 0.7, order: 7),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 6.3, duration: 0.7, order: 8),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 7.0, duration: 1.4, order: 9),
    ],
  ),

  // Nursery 5: Guitar - 머리 어깨 무릎 발
  Lesson(
    id: 'guitar_n02',
    title: '머리 어깨 무릎 발',
    description: '기타로 연주하는 머리 어깨 무릎 발! 빠른 템포에 도전해 보세요.',
    instrument: 'guitar',
    difficulty: 'beginner',
    durationMinutes: 7,
    imageEmoji: '🙋',
    bpm: 100,
    xpReward: 140,
    orderIndex: 34,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.0, duration: 0.6, order: 0),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.6, duration: 0.6, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.2, duration: 0.6, order: 2),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.8, duration: 0.6, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.4, duration: 0.6, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.0, duration: 0.6, order: 5),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 3.6, duration: 1.2, order: 6),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 4.8, duration: 0.6, order: 7),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 5.4, duration: 0.6, order: 8),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 6.0, duration: 0.6, order: 9),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 6.6, duration: 1.2, order: 10),
    ],
  ),

  // Nursery 6: Violin - 산토끼 (바이올린)
  Lesson(
    id: 'violin_n02',
    title: '산토끼 (바이올린)',
    description: '바이올린으로 산토끼를 연주합니다. A현과 E현을 사용합니다.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🐰',
    bpm: 85,
    xpReward: 150,
    orderIndex: 35,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 1.4, duration: 0.7, order: 2),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 2.1, duration: 0.7, order: 3),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 2.8, duration: 0.7, order: 4),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 3.5, duration: 0.7, order: 5),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 4.2, duration: 0.7, order: 6),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.9, duration: 0.7, order: 7),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.6, duration: 0.7, order: 8),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 6.3, duration: 0.7, order: 9),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 7.0, duration: 0.7, order: 10),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 7.7, duration: 1.4, order: 11),
    ],
  ),

  // Nursery 7: Violin - 곰 세 마리 (바이올린)
  Lesson(
    id: 'violin_n03',
    title: '곰 세 마리 (바이올린)',
    description: '바이올린으로 곰 세 마리를 연주합니다. 쉬운 운지로 시작해 보세요.',
    instrument: 'violin',
    difficulty: 'beginner',
    durationMinutes: 8,
    imageEmoji: '🐻',
    bpm: 85,
    xpReward: 150,
    orderIndex: 36,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.4, duration: 0.7, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 2.1, duration: 0.7, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 2.8, duration: 0.7, order: 4),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 3.5, duration: 0.7, order: 5),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 4.2, duration: 0.7, order: 6),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.9, duration: 0.7, order: 7),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.6, duration: 0.7, order: 8),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 6.3, duration: 0.7, order: 9),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 7.0, duration: 1.4, order: 10),
    ],
  ),

  // Nursery 8: Piano - 퐁당퐁당
  Lesson(
    id: 'piano_n07',
    title: '퐁당퐁당',
    description: '퐁당퐁당 물에 빠진 동요를 피아노로 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '💧',
    bpm: 85,
    xpReward: 130,
    orderIndex: 37,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.4, duration: 0.35, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.75, duration: 0.35, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.1, duration: 0.7, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.8, duration: 0.7, order: 5),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.5, duration: 1.4, order: 6),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 4.9, duration: 0.7, order: 7),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 5.6, duration: 0.7, order: 8),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.3, duration: 0.7, order: 9),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 7.0, duration: 1.4, order: 10),
    ],
  ),

  // Nursery 9: Drums - 동요 리듬 - 반짝반짝
  Lesson(
    id: 'drums_n01',
    title: '동요 리듬 - 반짝반짝',
    description: '반짝반짝 작은별의 리듬을 드럼으로 연주해 봅시다. 동요에 어울리는 비트!',
    instrument: 'drums',
    difficulty: 'beginner',
    durationMinutes: 7,
    imageEmoji: '⭐',
    bpm: 70,
    xpReward: 120,
    orderIndex: 38,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.0, duration: 0.4, order: 0),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 0.43, duration: 0.3, order: 1),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 0.86, duration: 0.4, order: 2),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 1.29, duration: 0.3, order: 3),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.72, duration: 0.4, order: 4),
      MusicNote(noteName: '하이햇', frequency: NoteFrequency.drumHihat, startTime: 2.15, duration: 0.3, order: 5),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 2.58, duration: 0.4, order: 6),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 3.44, duration: 0.8, order: 7),
    ],
  ),

  // Nursery 10: Piano - 꼬마 눈사람
  Lesson(
    id: 'piano_n08',
    title: '꼬마 눈사람',
    description: '겨울 동요 꼬마 눈사람을 피아노로 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'beginner',
    durationMinutes: 6,
    imageEmoji: '⛄',
    bpm: 85,
    xpReward: 130,
    orderIndex: 39,
    category: 'nursery',
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.7, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.7, duration: 0.7, order: 1),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.4, duration: 1.4, order: 2),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.8, duration: 0.7, order: 3),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.5, duration: 0.7, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 4.2, duration: 1.4, order: 5),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 5.6, duration: 0.7, order: 6),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 6.3, duration: 0.7, order: 7),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 7.0, duration: 0.7, order: 8),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.7, duration: 0.7, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 8.4, duration: 1.4, order: 10),
    ],
  ),

  // ═══════════════════════════════════════════════════════
  // ─── 추가 클래식 레슨 (Classic) ───
  // ═══════════════════════════════════════════════════════

  // Classic 1: Piano - 캉캉 (오펜바흐)
  Lesson(
    id: 'piano_c02',
    title: '캉캉 (오펜바흐)',
    description: '신나는 캉캉 멜로디! 오펜바흐의 유명한 곡을 피아노로 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 10,
    imageEmoji: '💃',
    bpm: 110,
    xpReward: 250,
    orderIndex: 40,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.0, duration: 0.27, order: 0),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 0.27, duration: 0.27, order: 1),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.54, duration: 0.27, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.81, duration: 0.27, order: 3),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.08, duration: 0.54, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 1.62, duration: 0.54, order: 5),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.16, duration: 0.54, order: 6),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 2.7, duration: 0.27, order: 7),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.97, duration: 0.27, order: 8),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 3.24, duration: 0.54, order: 9),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.78, duration: 0.54, order: 10),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 4.32, duration: 0.54, order: 11),
    ],
  ),

  // Classic 2: Piano - 터키 행진곡 (모차르트 인트로)
  Lesson(
    id: 'piano_c03',
    title: '터키 행진곡 (모차르트 인트로)',
    description: '모차르트 터키 행진곡의 유명한 도입부를 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🎼',
    bpm: 100,
    xpReward: 280,
    orderIndex: 41,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 0.0, duration: 0.3, order: 0),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.3, duration: 0.3, order: 1),
      MusicNote(noteName: 'G#4', frequency: NoteFrequency.gSharp4, startTime: 0.6, duration: 0.3, order: 2),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 0.9, duration: 0.6, order: 3),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.5, duration: 0.6, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 2.1, duration: 0.3, order: 5),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 2.4, duration: 0.3, order: 6),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 2.7, duration: 0.3, order: 7),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 3.0, duration: 0.6, order: 8),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 3.6, duration: 0.6, order: 9),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 4.2, duration: 0.3, order: 10),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 4.5, duration: 0.3, order: 11),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.8, duration: 0.3, order: 12),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.1, duration: 0.9, order: 13),
    ],
  ),

  // Classic 3: Piano - 미뉴에트 (바흐)
  Lesson(
    id: 'piano_c04',
    title: '미뉴에트 (바흐)',
    description: '바흐의 미뉴에트 G장조를 피아노로 연주해 봅시다. 우아한 3박자 클래식!',
    instrument: 'piano',
    difficulty: 'intermediate',
    durationMinutes: 10,
    imageEmoji: '🎼',
    bpm: 80,
    xpReward: 260,
    orderIndex: 42,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 0.0, duration: 0.75, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 0.75, duration: 0.375, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 1.125, duration: 0.375, order: 2),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 1.5, duration: 0.375, order: 3),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.875, duration: 0.375, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 2.25, duration: 0.75, order: 5),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.0, duration: 0.75, order: 6),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 3.75, duration: 0.75, order: 7),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 4.5, duration: 0.75, order: 8),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.25, duration: 0.375, order: 9),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 5.625, duration: 0.375, order: 10),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.0, duration: 0.375, order: 11),
      MusicNote(noteName: 'F#5', frequency: 739.99, startTime: 6.375, duration: 0.375, order: 12),
      MusicNote(noteName: 'G5', frequency: NoteFrequency.g5, startTime: 6.75, duration: 1.5, order: 13),
    ],
  ),

  // Classic 4: Guitar - 로망스 (인트로)
  Lesson(
    id: 'guitar_c01',
    title: '로망스 (인트로)',
    description: '기타 명곡 로망스의 도입부를 연주해 봅시다. 아르페지오의 기초!',
    instrument: 'guitar',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🌹',
    bpm: 70,
    xpReward: 260,
    orderIndex: 43,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 0.0, duration: 0.43, order: 0),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 0.43, duration: 0.43, order: 1),
      MusicNote(noteName: 'G#4', frequency: NoteFrequency.gSharp4, startTime: 0.86, duration: 0.43, order: 2),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 1.29, duration: 0.43, order: 3),
      MusicNote(noteName: 'G#4', frequency: NoteFrequency.gSharp4, startTime: 1.72, duration: 0.43, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 2.15, duration: 0.43, order: 5),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 2.58, duration: 0.43, order: 6),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.01, duration: 0.43, order: 7),
      MusicNote(noteName: 'G#4', frequency: NoteFrequency.gSharp4, startTime: 3.44, duration: 0.43, order: 8),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 3.87, duration: 0.43, order: 9),
      MusicNote(noteName: 'G#4', frequency: NoteFrequency.gSharp4, startTime: 4.3, duration: 0.43, order: 10),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 4.73, duration: 0.43, order: 11),
    ],
  ),

  // Classic 5: Guitar - 그린슬리브스
  Lesson(
    id: 'guitar_c02',
    title: '그린슬리브스',
    description: '영국 전통 민요 그린슬리브스를 기타로 연주해 봅시다. 아름다운 3박자 멜로디!',
    instrument: 'guitar',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🏰',
    bpm: 70,
    xpReward: 260,
    orderIndex: 44,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'A3', frequency: NoteFrequency.a3, startTime: 0.0, duration: 0.86, order: 0),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 0.86, duration: 1.72, order: 1),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 2.58, duration: 0.86, order: 2),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 3.44, duration: 1.29, order: 3),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 4.73, duration: 0.43, order: 4),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 5.16, duration: 0.86, order: 5),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 6.02, duration: 1.72, order: 6),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 7.74, duration: 0.86, order: 7),
      MusicNote(noteName: 'G3', frequency: NoteFrequency.g3, startTime: 8.6, duration: 1.29, order: 8),
      MusicNote(noteName: 'A3', frequency: NoteFrequency.a3, startTime: 9.89, duration: 0.43, order: 9),
      MusicNote(noteName: 'B3', frequency: NoteFrequency.b3, startTime: 10.32, duration: 0.86, order: 10),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 11.18, duration: 1.72, order: 11),
    ],
  ),

  // Classic 6: Violin - 봄 (비발디 인트로)
  Lesson(
    id: 'violin_c01',
    title: '봄 (비발디 인트로)',
    description: '비발디 사계 중 "봄"의 유명한 도입부를 바이올린으로 연주해 봅시다.',
    instrument: 'violin',
    difficulty: 'intermediate',
    durationMinutes: 10,
    imageEmoji: '🌸',
    bpm: 90,
    xpReward: 280,
    orderIndex: 45,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.0, duration: 0.66, order: 0),
      MusicNote(noteName: 'F5', frequency: NoteFrequency.f5, startTime: 0.66, duration: 0.33, order: 1),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.99, duration: 0.33, order: 2),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 1.32, duration: 0.33, order: 3),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 1.65, duration: 0.33, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 1.98, duration: 0.33, order: 5),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 2.31, duration: 0.66, order: 6),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 2.97, duration: 0.66, order: 7),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 3.63, duration: 1.32, order: 8),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.95, duration: 0.33, order: 9),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.28, duration: 0.33, order: 10),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 5.61, duration: 0.66, order: 11),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 6.27, duration: 0.66, order: 12),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 6.93, duration: 1.32, order: 13),
    ],
  ),

  // Classic 7: Violin - 캐논 (파헬벨 인트로)
  Lesson(
    id: 'violin_c02',
    title: '캐논 (파헬벨 인트로)',
    description: '파헬벨 캐논의 아름다운 선율을 바이올린으로 연주해 봅시다.',
    instrument: 'violin',
    difficulty: 'intermediate',
    durationMinutes: 12,
    imageEmoji: '🎼',
    bpm: 65,
    xpReward: 280,
    orderIndex: 46,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'F#5', frequency: 739.99, startTime: 0.0, duration: 0.92, order: 0),
      MusicNote(noteName: 'E5', frequency: NoteFrequency.e5, startTime: 0.92, duration: 0.92, order: 1),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 1.84, duration: 0.92, order: 2),
      MusicNote(noteName: 'C#5', frequency: 554.37, startTime: 2.76, duration: 0.92, order: 3),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 3.68, duration: 0.92, order: 4),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.6, duration: 0.92, order: 5),
      MusicNote(noteName: 'B4', frequency: NoteFrequency.b4, startTime: 5.52, duration: 0.92, order: 6),
      MusicNote(noteName: 'C#5', frequency: 554.37, startTime: 6.44, duration: 0.92, order: 7),
    ],
  ),

  // Classic 8: Piano - 꿈 (드뷔시 인트로)
  Lesson(
    id: 'piano_c05',
    title: '꿈 (드뷔시 인트로)',
    description: '드뷔시의 "꿈" 도입부를 피아노로 연주해 봅시다. 몽환적인 분위기!',
    instrument: 'piano',
    difficulty: 'advanced',
    durationMinutes: 15,
    imageEmoji: '🌙',
    bpm: 55,
    xpReward: 350,
    orderIndex: 47,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 0.0, duration: 1.09, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.09, duration: 1.09, order: 1),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 2.18, duration: 1.09, order: 2),
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 3.27, duration: 1.09, order: 3),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 4.36, duration: 0.545, order: 4),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 4.905, duration: 0.545, order: 5),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 5.45, duration: 1.09, order: 6),
      MusicNote(noteName: 'E4', frequency: NoteFrequency.e4, startTime: 6.54, duration: 0.545, order: 7),
      MusicNote(noteName: 'D4', frequency: NoteFrequency.d4, startTime: 7.085, duration: 0.545, order: 8),
      MusicNote(noteName: 'C4', frequency: NoteFrequency.c4, startTime: 7.63, duration: 2.18, order: 9),
    ],
  ),

  // Classic 9: Piano - 야상곡 (쇼팽 인트로)
  Lesson(
    id: 'piano_c06',
    title: '야상곡 (쇼팽 인트로)',
    description: '쇼팽 야상곡 Op.9 No.2의 아름다운 도입부를 연주해 봅시다.',
    instrument: 'piano',
    difficulty: 'advanced',
    durationMinutes: 15,
    imageEmoji: '🌃',
    bpm: 50,
    xpReward: 400,
    orderIndex: 48,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 0.0, duration: 1.2, order: 0),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 1.2, duration: 0.6, order: 1),
      MusicNote(noteName: 'F4', frequency: NoteFrequency.f4, startTime: 1.8, duration: 0.6, order: 2),
      MusicNote(noteName: 'G4', frequency: NoteFrequency.g4, startTime: 2.4, duration: 1.2, order: 3),
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 3.6, duration: 0.6, order: 4),
      MusicNote(noteName: 'D5', frequency: NoteFrequency.d5, startTime: 4.2, duration: 1.2, order: 5),
      MusicNote(noteName: 'C5', frequency: NoteFrequency.c5, startTime: 5.4, duration: 0.6, order: 6),
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 6.0, duration: 0.6, order: 7),
      MusicNote(noteName: 'A4', frequency: NoteFrequency.a4, startTime: 6.6, duration: 0.6, order: 8),
      MusicNote(noteName: 'Bb4', frequency: NoteFrequency.aSharp4, startTime: 7.2, duration: 2.4, order: 9),
    ],
  ),

  // Classic 10: Drums - 볼레로 리듬 (라벨)
  Lesson(
    id: 'drums_c01',
    title: '볼레로 리듬 (라벨)',
    description: '라벨의 볼레로! 유명한 스네어 드럼 리듬 패턴을 연습해 봅시다.',
    instrument: 'drums',
    difficulty: 'advanced',
    durationMinutes: 12,
    imageEmoji: '🥁',
    bpm: 72,
    xpReward: 350,
    orderIndex: 49,
    category: 'classic',
    isLocked: true,
    targetNotes: [
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.0, duration: 0.28, order: 0),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.28, duration: 0.28, order: 1),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.56, duration: 0.14, order: 2),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.7, duration: 0.14, order: 3),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.84, duration: 0.14, order: 4),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 0.98, duration: 0.28, order: 5),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.26, duration: 0.28, order: 6),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.54, duration: 0.14, order: 7),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.68, duration: 0.14, order: 8),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.82, duration: 0.14, order: 9),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 1.96, duration: 0.14, order: 10),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 2.1, duration: 0.14, order: 11),
      MusicNote(noteName: '스네어', frequency: NoteFrequency.drumSnare, startTime: 2.24, duration: 0.14, order: 12),
      MusicNote(noteName: '킥', frequency: NoteFrequency.drumKick, startTime: 2.52, duration: 0.28, order: 13),
    ],
  ),
];

// 전체 레슨 목록 프로바이더
final lessonListProvider = Provider<List<Lesson>>((ref) => _allLessons);

// 악기별 필터 프로바이더
final selectedInstrumentFilterProvider = StateProvider<String>((ref) => 'all');

// 카테고리 필터 프로바이더
final selectedCategoryFilterProvider = StateProvider<String>((ref) => 'all');

// 필터링된 레슨 목록 (구독 티어 + 카테고리 반영)
final filteredLessonsProvider = Provider<List<Lesson>>((ref) {
  final instrumentFilter = ref.watch(selectedInstrumentFilterProvider);
  final categoryFilter = ref.watch(selectedCategoryFilterProvider);
  final lessons = ref.watch(lessonListProvider);
  final isStandard = ref.watch(isStandardOrAboveProvider);
  final profile = ref.watch(userProfileProvider).valueOrNull;
  final selectedInstrument = profile?.selectedInstrument ?? 'piano';

  var result = lessons.toList();

  // 악기 필터
  if (instrumentFilter == 'all') {
    if (!isStandard) {
      result = result.where((l) => l.instrument == selectedInstrument).toList();
    }
  } else {
    result = result.where((l) => l.instrument == instrumentFilter).toList();
  }

  // 카테고리 필터
  if (categoryFilter != 'all') {
    result = result.where((l) => l.category == categoryFilter).toList();
  }

  return result;
});

// 특정 레슨 가져오기
final lessonByIdProvider = Provider.family<Lesson?, String>((ref, id) {
  return ref.watch(lessonListProvider).cast<Lesson?>().firstWhere(
    (l) => l?.id == id,
    orElse: () => null,
  );
});

// 추천 레슨 (입문 중 처음 3개)
final featuredLessonsProvider = Provider<List<Lesson>>((ref) {
  return ref
      .watch(lessonListProvider)
      .where((l) => l.difficulty == 'beginner')
      .take(3)
      .toList();
});
